// app
export const APP_URL = process.env.VUE_APP_URL;
export const APP_USER_TOKEN = process.env.VUE_APP_TOKEN;
// blockchain
export const BLOCKCHAIN_NAME = "STELLAR";
export const BLOCKCHAIN_NETWORK_TYPE = "testnet";
export const BLOCKCHAIN_NETWORK_NAME = "Test SDF Network ; September 2015";
export const BLOCKCHAIN_NETWORK_URI = "https://horizon-testnet.stellar.org";
export const BLOCKCHAIN_NETWORK_BASE_FEE_TYPE = "stroop";
export const BLOCKCHAIN_NETWORK_BASE_FEE_VALUE = 100;
export const BLOCKCHAIN_NETWORK_BASE_RESERVE_TYPE = "lumen";
export const BLOCKCHAIN_NETWORK_BASE_RESERVE_VALUE = 0.5;
// tx security
export const TX_PWD_SIGNATURE_ID = `MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDDAX/Pyt735VfbOBvVO+4FpxgV Uts92TzmF6r0HRGqBXJ8DOWWvDYqovZmCkPEVSqo8vinqoZywXpJWVP/8ffxuKCb bB7asTG1VyQU4UJzeHYKx0xj5s4U3iJxSPFSE8ZBvn/x8SbolV+Z9vubGLVqd0hs t8KRS0quKAbSIEqTpwIDAQAB`;
// error
export const ErrorCodes = Object.freeze({
  USER_TYPE: "USER_TYPE",
  TWO_FACTOR_AUTH: "TWO_FACTOR_AUTH",
  PHONE_AUTH: "PHONE_AUTH",
  ACCOUNT_APPROVAL: "ACCOUNT_APPROVAL",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  PASSWORD_VERIFICATION: "PASSWORD_VERIFICATION",
  PHONE_VERIFICATION: "PHONE_VERIFICATION",
  TWO_FACTOR_VERIFICATION: "TWO_FACTOR_VERIFICATION",
  TX_PASSWORD_VERIFICATION: "TX_PASSWORD_VERIFICATION"
});
