export const APP_URL = process.env.VUE_APP_URL;
export const APP_USER_TOKEN = process.env.VUE_APP_TOKEN;
export const ErrorCodes = Object.freeze({
  USER_TYPE: "USER_TYPE",
  TWO_FACTOR_AUTH: "TWO_FACTOR_AUTH",
  PHONE_AUTH: "PHONE_AUTH",
  ACCOUNT_APPROVAL: "ACCOUNT_APPROVAL",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  PASSWORD_VERIFICATION: "PASSWORD_VERIFICATION",
  PHONE_VERIFICATION: "PHONE_VERIFICATION",
  TWO_FACTOR_VERIFICATION: "TWO_FACTOR_VERIFICATION",
  TX_PASSWORD_VERIFICATION: "TX_PASSWORD_VERIFICATION"
});
